import { createContext } from 'react';

export type Language = 'en' | 'es';

export interface LanguageContextType {
  language: Language;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

export const translations = {
  en: {
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.projects': 'Projects',
    'nav.services': 'Services',
    'nav.contact': 'Contact',
    'hero.greeting': 'Hi, I\'m',
    'hero.name': 'Victor Huerta Davila',
    'hero.title': 'Full-Stack Developer Junior',
    'hero.description': 'I create digital and functional experiences that solve real-world problems. Specialized in modern web applications with a user-centered design approach.',
    'hero.cta.primary': 'View My Work',
    'hero.cta.secondary': 'Get In Touch',
    'about.title': 'About Me',
    'about.subtitle': 'Passionate developer creating meaningful solutions',
    'about.description': 'I have 4 years of continuous learning experience, specializing in building scalable web applications and mobile solutions. My approach combines clean code, modern design principles, and a deep understanding of user needs.',
    'about.experience.title': 'Experience & Education',
    'about.skills.title': 'Skills & Technologies',
    'projects.title': 'Featured Projects',
    'projects.subtitle': 'A selection of my recent work',
    'projects.filter.all': 'All',
    'projects.filter.web': 'Web',
    'projects.filter.mobile': 'Mobile',
    'projects.filter.design': 'Design',
    'projects.viewProject': 'View Project',
    'projects.viewCode': 'View Code',
    'services.title': 'What I Do',
    'services.subtitle': 'Comprehensive development services',
    'services.mobile.title': 'Mobile Apps',
    'services.mobile.description': 'Native and cross-platform mobile applications with intuitive interfaces and seamless performance.',
    'services.web.title': 'Web & Dashboards',
    'services.web.description': 'Modern web applications and analytics dashboards built with cutting-edge technologies.',
    'services.backend.title': 'Backend & APIs',
    'services.backend.description': 'Scalable server architectures, RESTful APIs, and database design for robust applications.',
    'contact.title': 'Let\'s Work Together',
    'contact.subtitle': 'Have a project in mind? Let\'s talk',
    'contact.form.name': 'Your Name',
    'contact.form.email': 'Email Address',
    'contact.form.message': 'Your Message',
    'contact.form.submit': 'Send Message',
    'contact.email': 'raihuerta01@gmail.com',
    'footer.copyright': '© 2026 Victor Huerta. All rights reserved.',
  },
  es: {
    'nav.home': 'Inicio',
    'nav.about': 'Sobre Mí',
    'nav.projects': 'Proyectos',
    'nav.services': 'Servicios',
    'nav.contact': 'Contacto',
    'hero.greeting': 'Hola, soy',
    'hero.name': 'Victor Huerta Davila',
    'hero.title': 'Desarrollador Full-Stack Junior',
    'hero.description': 'Creo experiencias digitales y funcionales que resuelven problemas reales. Especializado en aplicaciones web modernas con enfoque en diseño centrado en el usuario.',
    'hero.cta.primary': 'Ver Mi Trabajo',
    'hero.cta.secondary': 'Contáctame',
    'about.title': 'Sobre Mí',
    'about.subtitle': 'Desarrollador apasionado creando soluciones significativas',
    'about.description': 'Cuento con 4 años aprendiendo de manera continua, me especializo en construir aplicaciones web escalables y soluciones móviles. Mi enfoque combina código limpio, principios de diseño modernos y una profunda comprensión de las necesidades del usuario.',
    'about.experience.title': 'Experiencia & Educación',
    'about.skills.title': 'Habilidades y Tecnologías',
    'projects.title': 'Proyectos Destacados',
    'projects.subtitle': 'Una selección de mi trabajo reciente',
    'projects.filter.all': 'Todo',
    'projects.filter.web': 'Web',
    'projects.filter.mobile': 'Móvil',
    'projects.filter.design': 'Diseño',
    'projects.viewProject': 'Ver Proyecto',
    'projects.viewCode': 'Ver Código',
    'services.title': 'Lo Que Hago',
    'services.subtitle': 'Servicios de desarrollo integral',
    'services.mobile.title': 'Apps Móviles',
    'services.mobile.description': 'Aplicaciones móviles nativas y multiplataforma con interfaces intuitivas y rendimiento fluido.',
    'services.web.title': 'Web y Dashboards',
    'services.web.description': 'Aplicaciones web modernas y dashboards analíticos construidos con tecnologías de vanguardia.',
    'services.backend.title': 'Backend y APIs',
    'services.backend.description': 'Arquitecturas de servidor escalables, APIs RESTful y diseño de bases de datos para aplicaciones robustas.',
    'contact.title': 'Trabajemos Juntos',
    'contact.subtitle': '¿Tienes un proyecto en mente? Hablemos',
    'contact.form.name': 'Tu Nombre',
    'contact.form.email': 'Correo Electrónico',
    'contact.form.message': 'Tu Mensaje',
    'contact.form.submit': 'Enviar Mensaje',
    'contact.email': 'raihuerta01@gmail.com',
    'footer.copyright': '© 2026 Victor Huerta. Todos los derechos reservados.',
  },
} as const;

export const LanguageContext = createContext<LanguageContextType | undefined>(undefined);